services:
  mysql:
    image: mysql:8.2.0
    container_name: budget-db
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env

  app:
    build: .
    container_name: budget-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    env_file:
      - .env

volumes:
  db-data: