services:
  postgresql:
    image: postgres:16
    container_name: budget-db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env-local

volumes:
  db-data: